//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FaceWebApi.SSPP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Binding", Namespace="https://webservice.face.gob.es")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConsultarListadoFactura))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OGNIFs))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(OGUTOC))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Estado))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FacturaOffLine))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AnexoFile))]
    public partial class Service : Microsoft.Web.Services3.WebServicesClientProtocol
        {
        
        private System.Threading.SendOrPostCallback enviarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarListadoFacturasOffLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarListadoFacturasOffLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback anularFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEstadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUnidadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarNIFsOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarAdministracionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarAdministracionesRepositorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUnidadesPorAdministracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarNIFsPorAdministracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarListadoFacturasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::FaceWebApi.Properties.Settings.Default.FaceWebApi_SSPP_SSPPWebServiceProxyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enviarFacturaCompletedEventHandler enviarFacturaCompleted;
        
        /// <remarks/>
        public event enviarListadoFacturasOffLineCompletedEventHandler enviarListadoFacturasOffLineCompleted;
        
        /// <remarks/>
        public event consultarListadoFacturasOffLineCompletedEventHandler consultarListadoFacturasOffLineCompleted;
        
        /// <remarks/>
        public event consultarFacturaCompletedEventHandler consultarFacturaCompleted;
        
        /// <remarks/>
        public event anularFacturaCompletedEventHandler anularFacturaCompleted;
        
        /// <remarks/>
        public event consultarEstadosCompletedEventHandler consultarEstadosCompleted;
        
        /// <remarks/>
        public event consultarUnidadesCompletedEventHandler consultarUnidadesCompleted;
        
        /// <remarks/>
        public event consultarNIFsCompletedEventHandler consultarNIFsCompleted;
        
        /// <remarks/>
        public event consultarAdministracionesCompletedEventHandler consultarAdministracionesCompleted;
        
        /// <remarks/>
        public event consultarAdministracionesRepositorioCompletedEventHandler consultarAdministracionesRepositorioCompleted;
        
        /// <remarks/>
        public event consultarUnidadesPorAdministracionCompletedEventHandler consultarUnidadesPorAdministracionCompleted;
        
        /// <remarks/>
        public event consultarNIFsPorAdministracionCompletedEventHandler consultarNIFsPorAdministracionCompleted;
        
        /// <remarks/>
        public event consultarListadoFacturasCompletedEventHandler consultarListadoFacturasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#enviarFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public EnviarFacturaResponse enviarFactura(EnviarFacturaRequest request) {
            object[] results = this.Invoke("enviarFactura", new object[] {
                        request});
            return ((EnviarFacturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void enviarFacturaAsync(EnviarFacturaRequest request) {
            this.enviarFacturaAsync(request, null);
        }
        
        /// <remarks/>
        public void enviarFacturaAsync(EnviarFacturaRequest request, object userState) {
            if ((this.enviarFacturaOperationCompleted == null)) {
                this.enviarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarFacturaOperationCompleted);
            }
            this.InvokeAsync("enviarFactura", new object[] {
                        request}, this.enviarFacturaOperationCompleted, userState);
        }
        
        private void OnenviarFacturaOperationCompleted(object arg) {
            if ((this.enviarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarFacturaCompleted(this, new enviarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#enviarListadoFacturasOffLine", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public EnviarFacturaOffLineResponse enviarListadoFacturasOffLine(EnviarFacturaRequest[] request) {
            object[] results = this.Invoke("enviarListadoFacturasOffLine", new object[] {
                        request});
            return ((EnviarFacturaOffLineResponse)(results[0]));
        }
        
        /// <remarks/>
        public void enviarListadoFacturasOffLineAsync(EnviarFacturaRequest[] request) {
            this.enviarListadoFacturasOffLineAsync(request, null);
        }
        
        /// <remarks/>
        public void enviarListadoFacturasOffLineAsync(EnviarFacturaRequest[] request, object userState) {
            if ((this.enviarListadoFacturasOffLineOperationCompleted == null)) {
                this.enviarListadoFacturasOffLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarListadoFacturasOffLineOperationCompleted);
            }
            this.InvokeAsync("enviarListadoFacturasOffLine", new object[] {
                        request}, this.enviarListadoFacturasOffLineOperationCompleted, userState);
        }
        
        private void OnenviarListadoFacturasOffLineOperationCompleted(object arg) {
            if ((this.enviarListadoFacturasOffLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarListadoFacturasOffLineCompleted(this, new enviarListadoFacturasOffLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarListadoFacturasOffLine", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarListadoFacturasOffLineResponse consultarListadoFacturasOffLine(string idSolicitud) {
            object[] results = this.Invoke("consultarListadoFacturasOffLine", new object[] {
                        idSolicitud});
            return ((ConsultarListadoFacturasOffLineResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarListadoFacturasOffLineAsync(string idSolicitud) {
            this.consultarListadoFacturasOffLineAsync(idSolicitud, null);
        }
        
        /// <remarks/>
        public void consultarListadoFacturasOffLineAsync(string idSolicitud, object userState) {
            if ((this.consultarListadoFacturasOffLineOperationCompleted == null)) {
                this.consultarListadoFacturasOffLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarListadoFacturasOffLineOperationCompleted);
            }
            this.InvokeAsync("consultarListadoFacturasOffLine", new object[] {
                        idSolicitud}, this.consultarListadoFacturasOffLineOperationCompleted, userState);
        }
        
        private void OnconsultarListadoFacturasOffLineOperationCompleted(object arg) {
            if ((this.consultarListadoFacturasOffLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarListadoFacturasOffLineCompleted(this, new consultarListadoFacturasOffLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarFacturaResponse consultarFactura(string numeroRegistro) {
            object[] results = this.Invoke("consultarFactura", new object[] {
                        numeroRegistro});
            return ((ConsultarFacturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarFacturaAsync(string numeroRegistro) {
            this.consultarFacturaAsync(numeroRegistro, null);
        }
        
        /// <remarks/>
        public void consultarFacturaAsync(string numeroRegistro, object userState) {
            if ((this.consultarFacturaOperationCompleted == null)) {
                this.consultarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarFacturaOperationCompleted);
            }
            this.InvokeAsync("consultarFactura", new object[] {
                        numeroRegistro}, this.consultarFacturaOperationCompleted, userState);
        }
        
        private void OnconsultarFacturaOperationCompleted(object arg) {
            if ((this.consultarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarFacturaCompleted(this, new consultarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#anularFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AnularFacturaResponse anularFactura(string numeroRegistro, string motivo) {
            object[] results = this.Invoke("anularFactura", new object[] {
                        numeroRegistro,
                        motivo});
            return ((AnularFacturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void anularFacturaAsync(string numeroRegistro, string motivo) {
            this.anularFacturaAsync(numeroRegistro, motivo, null);
        }
        
        /// <remarks/>
        public void anularFacturaAsync(string numeroRegistro, string motivo, object userState) {
            if ((this.anularFacturaOperationCompleted == null)) {
                this.anularFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnanularFacturaOperationCompleted);
            }
            this.InvokeAsync("anularFactura", new object[] {
                        numeroRegistro,
                        motivo}, this.anularFacturaOperationCompleted, userState);
        }
        
        private void OnanularFacturaOperationCompleted(object arg) {
            if ((this.anularFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.anularFacturaCompleted(this, new anularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarEstados", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarEstadosResponse consultarEstados() {
            object[] results = this.Invoke("consultarEstados", new object[0]);
            return ((ConsultarEstadosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEstadosAsync() {
            this.consultarEstadosAsync(null);
        }
        
        /// <remarks/>
        public void consultarEstadosAsync(object userState) {
            if ((this.consultarEstadosOperationCompleted == null)) {
                this.consultarEstadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEstadosOperationCompleted);
            }
            this.InvokeAsync("consultarEstados", new object[0], this.consultarEstadosOperationCompleted, userState);
        }
        
        private void OnconsultarEstadosOperationCompleted(object arg) {
            if ((this.consultarEstadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEstadosCompleted(this, new consultarEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidades", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarRelacionesResponse consultarUnidades() {
            object[] results = this.Invoke("consultarUnidades", new object[0]);
            return ((ConsultarRelacionesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUnidadesAsync() {
            this.consultarUnidadesAsync(null);
        }
        
        /// <remarks/>
        public void consultarUnidadesAsync(object userState) {
            if ((this.consultarUnidadesOperationCompleted == null)) {
                this.consultarUnidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUnidadesOperationCompleted);
            }
            this.InvokeAsync("consultarUnidades", new object[0], this.consultarUnidadesOperationCompleted, userState);
        }
        
        private void OnconsultarUnidadesOperationCompleted(object arg) {
            if ((this.consultarUnidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUnidadesCompleted(this, new consultarUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarNIFs", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarNIFsResponse consultarNIFs() {
            object[] results = this.Invoke("consultarNIFs", new object[0]);
            return ((ConsultarNIFsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarNIFsAsync() {
            this.consultarNIFsAsync(null);
        }
        
        /// <remarks/>
        public void consultarNIFsAsync(object userState) {
            if ((this.consultarNIFsOperationCompleted == null)) {
                this.consultarNIFsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarNIFsOperationCompleted);
            }
            this.InvokeAsync("consultarNIFs", new object[0], this.consultarNIFsOperationCompleted, userState);
        }
        
        private void OnconsultarNIFsOperationCompleted(object arg) {
            if ((this.consultarNIFsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarNIFsCompleted(this, new consultarNIFsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministraciones", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarAdministracionesResponse consultarAdministraciones() {
            object[] results = this.Invoke("consultarAdministraciones", new object[0]);
            return ((ConsultarAdministracionesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAdministracionesAsync() {
            this.consultarAdministracionesAsync(null);
        }
        
        /// <remarks/>
        public void consultarAdministracionesAsync(object userState) {
            if ((this.consultarAdministracionesOperationCompleted == null)) {
                this.consultarAdministracionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarAdministracionesOperationCompleted);
            }
            this.InvokeAsync("consultarAdministraciones", new object[0], this.consultarAdministracionesOperationCompleted, userState);
        }
        
        private void OnconsultarAdministracionesOperationCompleted(object arg) {
            if ((this.consultarAdministracionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarAdministracionesCompleted(this, new consultarAdministracionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministracionesRepositorio", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarAdministracionesRepositorioResponse consultarAdministracionesRepositorio() {
            object[] results = this.Invoke("consultarAdministracionesRepositorio", new object[0]);
            return ((ConsultarAdministracionesRepositorioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAdministracionesRepositorioAsync() {
            this.consultarAdministracionesRepositorioAsync(null);
        }
        
        /// <remarks/>
        public void consultarAdministracionesRepositorioAsync(object userState) {
            if ((this.consultarAdministracionesRepositorioOperationCompleted == null)) {
                this.consultarAdministracionesRepositorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarAdministracionesRepositorioOperationCompleted);
            }
            this.InvokeAsync("consultarAdministracionesRepositorio", new object[0], this.consultarAdministracionesRepositorioOperationCompleted, userState);
        }
        
        private void OnconsultarAdministracionesRepositorioOperationCompleted(object arg) {
            if ((this.consultarAdministracionesRepositorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarAdministracionesRepositorioCompleted(this, new consultarAdministracionesRepositorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidadesPorAdministracion", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarRelacionesPorAdministracionResponse consultarUnidadesPorAdministracion(string codigoDir) {
            object[] results = this.Invoke("consultarUnidadesPorAdministracion", new object[] {
                        codigoDir});
            return ((ConsultarRelacionesPorAdministracionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUnidadesPorAdministracionAsync(string codigoDir) {
            this.consultarUnidadesPorAdministracionAsync(codigoDir, null);
        }
        
        /// <remarks/>
        public void consultarUnidadesPorAdministracionAsync(string codigoDir, object userState) {
            if ((this.consultarUnidadesPorAdministracionOperationCompleted == null)) {
                this.consultarUnidadesPorAdministracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUnidadesPorAdministracionOperationCompleted);
            }
            this.InvokeAsync("consultarUnidadesPorAdministracion", new object[] {
                        codigoDir}, this.consultarUnidadesPorAdministracionOperationCompleted, userState);
        }
        
        private void OnconsultarUnidadesPorAdministracionOperationCompleted(object arg) {
            if ((this.consultarUnidadesPorAdministracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUnidadesPorAdministracionCompleted(this, new consultarUnidadesPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarNIFsPorAdministracion", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultarNIFsPorAdministracionResponse consultarNIFsPorAdministracion(string codigoDir) {
            object[] results = this.Invoke("consultarNIFsPorAdministracion", new object[] {
                        codigoDir});
            return ((ConsultarNIFsPorAdministracionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarNIFsPorAdministracionAsync(string codigoDir) {
            this.consultarNIFsPorAdministracionAsync(codigoDir, null);
        }
        
        /// <remarks/>
        public void consultarNIFsPorAdministracionAsync(string codigoDir, object userState) {
            if ((this.consultarNIFsPorAdministracionOperationCompleted == null)) {
                this.consultarNIFsPorAdministracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarNIFsPorAdministracionOperationCompleted);
            }
            this.InvokeAsync("consultarNIFsPorAdministracion", new object[] {
                        codigoDir}, this.consultarNIFsPorAdministracionOperationCompleted, userState);
        }
        
        private void OnconsultarNIFsPorAdministracionOperationCompleted(object arg) {
            if ((this.consultarNIFsPorAdministracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarNIFsPorAdministracionCompleted(this, new consultarNIFsPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarListadoFacturas", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ConsultaListadoFacturaResponse consultarListadoFacturas(object[] request) {
            object[] results = this.Invoke("consultarListadoFacturas", new object[] {
                        request});
            return ((ConsultaListadoFacturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void consultarListadoFacturasAsync(object[] request) {
            this.consultarListadoFacturasAsync(request, null);
        }
        
        /// <remarks/>
        public void consultarListadoFacturasAsync(object[] request, object userState) {
            if ((this.consultarListadoFacturasOperationCompleted == null)) {
                this.consultarListadoFacturasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarListadoFacturasOperationCompleted);
            }
            this.InvokeAsync("consultarListadoFacturas", new object[] {
                        request}, this.consultarListadoFacturasOperationCompleted, userState);
        }
        
        private void OnconsultarListadoFacturasOperationCompleted(object arg) {
            if ((this.consultarListadoFacturasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarListadoFacturasCompleted(this, new consultarListadoFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class EnviarFacturaRequest {
        
        private string correoField;
        
        private FacturaFile facturaField;
        
        private AnexoFile[] anexosField;
        
        /// <comentarios/>
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        public FacturaFile factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public AnexoFile[] anexos {
            get {
                return this.anexosField;
            }
            set {
                this.anexosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class FacturaFile {
        
        private string facturaField;
        
        private string nombreField;
        
        private string mimeField;
        
        /// <comentarios/>
        public string factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string mime {
            get {
                return this.mimeField;
            }
            set {
                this.mimeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarListadoFactura {
        
        private string codigoField;
        
        private string descripcionField;
        
        private ConsultarFactura facturaField;
        
        /// <comentarios/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public ConsultarFactura factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarFactura {
        
        private string numeroRegistroField;
        
        private EstadoFactura tramitacionField;
        
        private EstadoFactura anulacionField;
        
        /// <comentarios/>
        public string numeroRegistro {
            get {
                return this.numeroRegistroField;
            }
            set {
                this.numeroRegistroField = value;
            }
        }
        
        /// <comentarios/>
        public EstadoFactura tramitacion {
            get {
                return this.tramitacionField;
            }
            set {
                this.tramitacionField = value;
            }
        }
        
        /// <comentarios/>
        public EstadoFactura anulacion {
            get {
                return this.anulacionField;
            }
            set {
                this.anulacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class EstadoFactura {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string motivoField;
        
        /// <comentarios/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultaListadoFacturaResponse {
        
        private Resultado resultadoField;
        
        private ConsultarListadoFactura[] facturasField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ConsultarListadoFactura[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class Resultado {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string codigoSeguimientoField;
        
        /// <comentarios/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoSeguimiento {
            get {
                return this.codigoSeguimientoField;
            }
            set {
                this.codigoSeguimientoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarNIFsPorAdministracionResponse {
        
        private Resultado resultadoField;
        
        private OGNIFs[] nifsField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public OGNIFs[] nifs {
            get {
                return this.nifsField;
            }
            set {
                this.nifsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class OGNIFs {
        
        private UnidadDir3 organoGestorField;
        
        private string nifField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3 organoGestor {
            get {
                return this.organoGestorField;
            }
            set {
                this.organoGestorField = value;
            }
        }
        
        /// <comentarios/>
        public string nif {
            get {
                return this.nifField;
            }
            set {
                this.nifField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class UnidadDir3 {
        
        private string codigoField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarRelacionesPorAdministracionResponse {
        
        private Resultado resultadoField;
        
        private OGUTOC[] relacionesField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public OGUTOC[] relaciones {
            get {
                return this.relacionesField;
            }
            set {
                this.relacionesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class OGUTOC {
        
        private UnidadDir3 organoGestorField;
        
        private UnidadDir3 unidadTramitadoraField;
        
        private UnidadDir3 oficinaContableField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3 organoGestor {
            get {
                return this.organoGestorField;
            }
            set {
                this.organoGestorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3 unidadTramitadora {
            get {
                return this.unidadTramitadoraField;
            }
            set {
                this.unidadTramitadoraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3 oficinaContable {
            get {
                return this.oficinaContableField;
            }
            set {
                this.oficinaContableField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarAdministracionesRepositorioResponse {
        
        private Resultado resultadoField;
        
        private UnidadDir3[] administracionesField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3[] administraciones {
            get {
                return this.administracionesField;
            }
            set {
                this.administracionesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarAdministracionesResponse {
        
        private Resultado resultadoField;
        
        private UnidadDir3[] administracionesField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public UnidadDir3[] administraciones {
            get {
                return this.administracionesField;
            }
            set {
                this.administracionesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarNIFsResponse {
        
        private Resultado resultadoField;
        
        private OGNIFs[] nifsField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public OGNIFs[] nifs {
            get {
                return this.nifsField;
            }
            set {
                this.nifsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarRelacionesResponse {
        
        private Resultado resultadoField;
        
        private OGUTOC[] relacionesField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public OGUTOC[] relaciones {
            get {
                return this.relacionesField;
            }
            set {
                this.relacionesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class Estado {
        
        private string nombreField;
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarEstadosResponse {
        
        private Resultado resultadoField;
        
        private Estado[] estadosField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Estado[] estados {
            get {
                return this.estadosField;
            }
            set {
                this.estadosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class AnularFactura {
        
        private string numeroRegistroField;
        
        private string mensajeField;
        
        /// <comentarios/>
        public string numeroRegistro {
            get {
                return this.numeroRegistroField;
            }
            set {
                this.numeroRegistroField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class AnularFacturaResponse {
        
        private Resultado resultadoField;
        
        private AnularFactura facturaField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public AnularFactura factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarFacturaResponse {
        
        private Resultado resultadoField;
        
        private ConsultarFactura facturaField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ConsultarFactura factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class FacturaOffLine {
        
        private string codigoField;
        
        private string descripcionField;
        
        private EnviarFactura facturaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public EnviarFactura factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class EnviarFactura {
        
        private string numeroRegistroField;
        
        private string organoGestorField;
        
        private string unidadTramitadoraField;
        
        private string oficinaContableField;
        
        private string identificadorEmisorField;
        
        private string numeroFacturaField;
        
        private string serieFacturaField;
        
        private string fechaRecepcionField;
        
        /// <comentarios/>
        public string numeroRegistro {
            get {
                return this.numeroRegistroField;
            }
            set {
                this.numeroRegistroField = value;
            }
        }
        
        /// <comentarios/>
        public string organoGestor {
            get {
                return this.organoGestorField;
            }
            set {
                this.organoGestorField = value;
            }
        }
        
        /// <comentarios/>
        public string unidadTramitadora {
            get {
                return this.unidadTramitadoraField;
            }
            set {
                this.unidadTramitadoraField = value;
            }
        }
        
        /// <comentarios/>
        public string oficinaContable {
            get {
                return this.oficinaContableField;
            }
            set {
                this.oficinaContableField = value;
            }
        }
        
        /// <comentarios/>
        public string identificadorEmisor {
            get {
                return this.identificadorEmisorField;
            }
            set {
                this.identificadorEmisorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string serieFactura {
            get {
                return this.serieFacturaField;
            }
            set {
                this.serieFacturaField = value;
            }
        }
        
        /// <comentarios/>
        public string fechaRecepcion {
            get {
                return this.fechaRecepcionField;
            }
            set {
                this.fechaRecepcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarListadoFacturasOffLine {
        
        private string estadoField;
        
        private FacturaOffLine[] facturasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FacturaOffLine[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ConsultarListadoFacturasOffLineResponse {
        
        private Resultado resultadoField;
        
        private ConsultarListadoFacturasOffLine solicitudField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ConsultarListadoFacturasOffLine solicitud {
            get {
                return this.solicitudField;
            }
            set {
                this.solicitudField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class Solicitud {
        
        private string numSolicitudField;
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numSolicitud {
            get {
                return this.numSolicitudField;
            }
            set {
                this.numSolicitudField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class EnviarFacturaOffLineResponse {
        
        private Resultado resultadoField;
        
        private Solicitud solicitudField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Solicitud solicitud {
            get {
                return this.solicitudField;
            }
            set {
                this.solicitudField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class EnviarFacturaResponse {
        
        private Resultado resultadoField;
        
        private EnviarFactura facturaField;
        
        /// <comentarios/>
        public Resultado resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public EnviarFactura factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class AnexoFile {
        
        private string anexoField;
        
        private string nombreField;
        
        private string mimeField;
        
        /// <comentarios/>
        public string anexo {
            get {
                return this.anexoField;
            }
            set {
                this.anexoField = value;
            }
        }
        
        /// <comentarios/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string mime {
            get {
                return this.mimeField;
            }
            set {
                this.mimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void enviarFacturaCompletedEventHandler(object sender, enviarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnviarFacturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnviarFacturaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void enviarListadoFacturasOffLineCompletedEventHandler(object sender, enviarListadoFacturasOffLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarListadoFacturasOffLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarListadoFacturasOffLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnviarFacturaOffLineResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnviarFacturaOffLineResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarListadoFacturasOffLineCompletedEventHandler(object sender, consultarListadoFacturasOffLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarListadoFacturasOffLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarListadoFacturasOffLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarListadoFacturasOffLineResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarListadoFacturasOffLineResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarFacturaCompletedEventHandler(object sender, consultarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarFacturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarFacturaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void anularFacturaCompletedEventHandler(object sender, anularFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class anularFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal anularFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AnularFacturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AnularFacturaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarEstadosCompletedEventHandler(object sender, consultarEstadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEstadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEstadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarEstadosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarEstadosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarUnidadesCompletedEventHandler(object sender, consultarUnidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUnidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUnidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarRelacionesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarRelacionesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarNIFsCompletedEventHandler(object sender, consultarNIFsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarNIFsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarNIFsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarNIFsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarNIFsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarAdministracionesCompletedEventHandler(object sender, consultarAdministracionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarAdministracionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarAdministracionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarAdministracionesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarAdministracionesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarAdministracionesRepositorioCompletedEventHandler(object sender, consultarAdministracionesRepositorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarAdministracionesRepositorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarAdministracionesRepositorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarAdministracionesRepositorioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarAdministracionesRepositorioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarUnidadesPorAdministracionCompletedEventHandler(object sender, consultarUnidadesPorAdministracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUnidadesPorAdministracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUnidadesPorAdministracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarRelacionesPorAdministracionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarRelacionesPorAdministracionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarNIFsPorAdministracionCompletedEventHandler(object sender, consultarNIFsPorAdministracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarNIFsPorAdministracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarNIFsPorAdministracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarNIFsPorAdministracionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarNIFsPorAdministracionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void consultarListadoFacturasCompletedEventHandler(object sender, consultarListadoFacturasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarListadoFacturasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarListadoFacturasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultaListadoFacturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultaListadoFacturaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591