//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
// 
#pragma warning disable 1591

namespace FaceWebApi.SPP2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SSPPWebServiceProxyBinding", Namespace="https://webservice.face.gob.es")]
    public partial class SSPPWebServiceProxyService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback enviarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback anularFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEstadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUnidadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarAdministracionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUnidadesPorAdministracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarListadoFacturasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SSPPWebServiceProxyService() {
            this.Url = global::FaceWebApi.Properties.Settings.Default.FaceWebApi_SPP2_SSPPWebServiceProxyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enviarFacturaCompletedEventHandler enviarFacturaCompleted;
        
        /// <remarks/>
        public event consultarFacturaCompletedEventHandler consultarFacturaCompleted;
        
        /// <remarks/>
        public event anularFacturaCompletedEventHandler anularFacturaCompleted;
        
        /// <remarks/>
        public event consultarEstadosCompletedEventHandler consultarEstadosCompleted;
        
        /// <remarks/>
        public event consultarUnidadesCompletedEventHandler consultarUnidadesCompleted;
        
        /// <remarks/>
        public event consultarAdministracionesCompletedEventHandler consultarAdministracionesCompleted;
        
        /// <remarks/>
        public event consultarUnidadesPorAdministracionCompletedEventHandler consultarUnidadesPorAdministracionCompleted;
        
        /// <remarks/>
        public event consultarListadoFacturasCompletedEventHandler consultarListadoFacturasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#enviarFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPResultadoEnviarFactura enviarFactura(SSPPFactura facturaWS) {
            object[] results = this.Invoke("enviarFactura", new object[] {
                        facturaWS});
            return ((SSPPResultadoEnviarFactura)(results[0]));
        }
        
        /// <remarks/>
        public void enviarFacturaAsync(SSPPFactura facturaWS) {
            this.enviarFacturaAsync(facturaWS, null);
        }
        
        /// <remarks/>
        public void enviarFacturaAsync(SSPPFactura facturaWS, object userState) {
            if ((this.enviarFacturaOperationCompleted == null)) {
                this.enviarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarFacturaOperationCompleted);
            }
            this.InvokeAsync("enviarFactura", new object[] {
                        facturaWS}, this.enviarFacturaOperationCompleted, userState);
        }
        
        private void OnenviarFacturaOperationCompleted(object arg) {
            if ((this.enviarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarFacturaCompleted(this, new enviarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPResultadoConsultarFactura consultarFactura(string numeroRegistro) {
            object[] results = this.Invoke("consultarFactura", new object[] {
                        numeroRegistro});
            return ((SSPPResultadoConsultarFactura)(results[0]));
        }
        
        /// <remarks/>
        public void consultarFacturaAsync(string numeroRegistro) {
            this.consultarFacturaAsync(numeroRegistro, null);
        }
        
        /// <remarks/>
        public void consultarFacturaAsync(string numeroRegistro, object userState) {
            if ((this.consultarFacturaOperationCompleted == null)) {
                this.consultarFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarFacturaOperationCompleted);
            }
            this.InvokeAsync("consultarFactura", new object[] {
                        numeroRegistro}, this.consultarFacturaOperationCompleted, userState);
        }
        
        private void OnconsultarFacturaOperationCompleted(object arg) {
            if ((this.consultarFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarFacturaCompleted(this, new consultarFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#anularFactura", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPResultadoAnularFactura anularFactura(string numeroRegistro, string motivo) {
            object[] results = this.Invoke("anularFactura", new object[] {
                        numeroRegistro,
                        motivo});
            return ((SSPPResultadoAnularFactura)(results[0]));
        }
        
        /// <remarks/>
        public void anularFacturaAsync(string numeroRegistro, string motivo) {
            this.anularFacturaAsync(numeroRegistro, motivo, null);
        }
        
        /// <remarks/>
        public void anularFacturaAsync(string numeroRegistro, string motivo, object userState) {
            if ((this.anularFacturaOperationCompleted == null)) {
                this.anularFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnanularFacturaOperationCompleted);
            }
            this.InvokeAsync("anularFactura", new object[] {
                        numeroRegistro,
                        motivo}, this.anularFacturaOperationCompleted, userState);
        }
        
        private void OnanularFacturaOperationCompleted(object arg) {
            if ((this.anularFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.anularFacturaCompleted(this, new anularFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarEstados", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPEstados consultarEstados() {
            object[] results = this.Invoke("consultarEstados", new object[0]);
            return ((SSPPEstados)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEstadosAsync() {
            this.consultarEstadosAsync(null);
        }
        
        /// <remarks/>
        public void consultarEstadosAsync(object userState) {
            if ((this.consultarEstadosOperationCompleted == null)) {
                this.consultarEstadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEstadosOperationCompleted);
            }
            this.InvokeAsync("consultarEstados", new object[0], this.consultarEstadosOperationCompleted, userState);
        }
        
        private void OnconsultarEstadosOperationCompleted(object arg) {
            if ((this.consultarEstadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEstadosCompleted(this, new consultarEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidades", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPResultadoConsultarUnidades consultarUnidades() {
            object[] results = this.Invoke("consultarUnidades", new object[0]);
            return ((SSPPResultadoConsultarUnidades)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUnidadesAsync() {
            this.consultarUnidadesAsync(null);
        }
        
        /// <remarks/>
        public void consultarUnidadesAsync(object userState) {
            if ((this.consultarUnidadesOperationCompleted == null)) {
                this.consultarUnidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUnidadesOperationCompleted);
            }
            this.InvokeAsync("consultarUnidades", new object[0], this.consultarUnidadesOperationCompleted, userState);
        }
        
        private void OnconsultarUnidadesOperationCompleted(object arg) {
            if ((this.consultarUnidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUnidadesCompleted(this, new consultarUnidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarAdministraciones", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ArrayOfSSPPUnidadDir consultarAdministraciones() {
            object[] results = this.Invoke("consultarAdministraciones", new object[0]);
            return ((ArrayOfSSPPUnidadDir)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAdministracionesAsync() {
            this.consultarAdministracionesAsync(null);
        }
        
        /// <remarks/>
        public void consultarAdministracionesAsync(object userState) {
            if ((this.consultarAdministracionesOperationCompleted == null)) {
                this.consultarAdministracionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarAdministracionesOperationCompleted);
            }
            this.InvokeAsync("consultarAdministraciones", new object[0], this.consultarAdministracionesOperationCompleted, userState);
        }
        
        private void OnconsultarAdministracionesOperationCompleted(object arg) {
            if ((this.consultarAdministracionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarAdministracionesCompleted(this, new consultarAdministracionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarUnidadesPorAdministracion", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public SSPPResultadoConsultarUnidades consultarUnidadesPorAdministracion(string codigoDir) {
            object[] results = this.Invoke("consultarUnidadesPorAdministracion", new object[] {
                        codigoDir});
            return ((SSPPResultadoConsultarUnidades)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUnidadesPorAdministracionAsync(string codigoDir) {
            this.consultarUnidadesPorAdministracionAsync(codigoDir, null);
        }
        
        /// <remarks/>
        public void consultarUnidadesPorAdministracionAsync(string codigoDir, object userState) {
            if ((this.consultarUnidadesPorAdministracionOperationCompleted == null)) {
                this.consultarUnidadesPorAdministracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUnidadesPorAdministracionOperationCompleted);
            }
            this.InvokeAsync("consultarUnidadesPorAdministracion", new object[] {
                        codigoDir}, this.consultarUnidadesPorAdministracionOperationCompleted, userState);
        }
        
        private void OnconsultarUnidadesPorAdministracionOperationCompleted(object arg) {
            if ((this.consultarUnidadesPorAdministracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUnidadesPorAdministracionCompleted(this, new consultarUnidadesPorAdministracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://webservice.face.gob.es#consultarListadoFacturas", RequestNamespace="https://webservice.face.gob.es", ResponseNamespace="https://webservice.face.gob.es", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ArrayOfSSPPResultadoConsultarFactura consultarListadoFacturas(Array listadoFacturas) {
            object[] results = this.Invoke("consultarListadoFacturas", new object[] {
                        listadoFacturas});
            return ((ArrayOfSSPPResultadoConsultarFactura)(results[0]));
        }
        
        /// <remarks/>
        public void consultarListadoFacturasAsync(Array listadoFacturas) {
            this.consultarListadoFacturasAsync(listadoFacturas, null);
        }
        
        /// <remarks/>
        public void consultarListadoFacturasAsync(Array listadoFacturas, object userState) {
            if ((this.consultarListadoFacturasOperationCompleted == null)) {
                this.consultarListadoFacturasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarListadoFacturasOperationCompleted);
            }
            this.InvokeAsync("consultarListadoFacturas", new object[] {
                        listadoFacturas}, this.consultarListadoFacturasOperationCompleted, userState);
        }
        
        private void OnconsultarListadoFacturasOperationCompleted(object arg) {
            if ((this.consultarListadoFacturasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarListadoFacturasCompleted(this, new consultarListadoFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPFactura {
        
        private string correoField;
        
        private SSPPFicheroFactura fichero_facturaField;
        
        private ArrayOfSSPPFicheroAnexo ficheros_anexosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SSPPFicheroFactura fichero_factura {
            get {
                return this.fichero_facturaField;
            }
            set {
                this.fichero_facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ArrayOfSSPPFicheroAnexo ficheros_anexos {
            get {
                return this.ficheros_anexosField;
            }
            set {
                this.ficheros_anexosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPFicheroFactura {
        
        private string facturaField;
        
        private string nombreField;
        
        private string mimeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mime {
            get {
                return this.mimeField;
            }
            set {
                this.mimeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPResultadoConsultarUnidades {
        
        private ArrayOfSSPPOrganoGestorUnidadTramitadora unidadesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ArrayOfSSPPOrganoGestorUnidadTramitadora unidades {
            get {
                return this.unidadesField;
            }
            set {
                this.unidadesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ArrayOfSSPPOrganoGestorUnidadTramitadora : Array {
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayOfSSPPResultadoConsultarFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayOfSSPPUnidadDir))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayOfSSPPOrganoGestorUnidadTramitadora))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayOfSSPPEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayOfSSPPFicheroAnexo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/encoding/")]
    public partial class Array {
        
        private System.Xml.XmlElement[] anyField;
        
        private string arrayTypeField;
        
        private string offsetField;
        
        private bool offsetFieldSpecified;
        
        private string idField;
        
        private string hrefField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string arrayType {
            get {
                return this.arrayTypeField;
            }
            set {
                this.arrayTypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified {
            get {
                return this.offsetFieldSpecified;
            }
            set {
                this.offsetFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ArrayOfSSPPResultadoConsultarFactura : Array {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ArrayOfSSPPUnidadDir : Array {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ArrayOfSSPPEstado : Array {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class ArrayOfSSPPFicheroAnexo : Array {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPEstados {
        
        private ArrayOfSSPPEstado estadosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ArrayOfSSPPEstado estados {
            get {
                return this.estadosField;
            }
            set {
                this.estadosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPResultadoAnularFactura {
        
        private string numero_registroField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numero_registro {
            get {
                return this.numero_registroField;
            }
            set {
                this.numero_registroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPResultadoConsultarFacturaEstado {
        
        private string codigo_estadoField;
        
        private string descripcion_estadoField;
        
        private string motivo_estadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string codigo_estado {
            get {
                return this.codigo_estadoField;
            }
            set {
                this.codigo_estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string descripcion_estado {
            get {
                return this.descripcion_estadoField;
            }
            set {
                this.descripcion_estadoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string motivo_estado {
            get {
                return this.motivo_estadoField;
            }
            set {
                this.motivo_estadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPResultadoConsultarFactura {
        
        private string numero_registroField;
        
        private SSPPResultadoConsultarFacturaEstado tramitacionField;
        
        private SSPPResultadoConsultarFacturaEstado anulacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numero_registro {
            get {
                return this.numero_registroField;
            }
            set {
                this.numero_registroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SSPPResultadoConsultarFacturaEstado tramitacion {
            get {
                return this.tramitacionField;
            }
            set {
                this.tramitacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public SSPPResultadoConsultarFacturaEstado anulacion {
            get {
                return this.anulacionField;
            }
            set {
                this.anulacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.face.gob.es")]
    public partial class SSPPResultadoEnviarFactura {
        
        private string codigo_registroField;
        
        private string organo_gestorField;
        
        private string unidad_tramitadoraField;
        
        private string oficina_contableField;
        
        private string identificador_emisorField;
        
        private string numero_facturaField;
        
        private string serie_facturaField;
        
        private string fecha_recepcionField;
        
        private string pdf_justificanteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string codigo_registro {
            get {
                return this.codigo_registroField;
            }
            set {
                this.codigo_registroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string organo_gestor {
            get {
                return this.organo_gestorField;
            }
            set {
                this.organo_gestorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string unidad_tramitadora {
            get {
                return this.unidad_tramitadoraField;
            }
            set {
                this.unidad_tramitadoraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string oficina_contable {
            get {
                return this.oficina_contableField;
            }
            set {
                this.oficina_contableField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string identificador_emisor {
            get {
                return this.identificador_emisorField;
            }
            set {
                this.identificador_emisorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string numero_factura {
            get {
                return this.numero_facturaField;
            }
            set {
                this.numero_facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serie_factura {
            get {
                return this.serie_facturaField;
            }
            set {
                this.serie_facturaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fecha_recepcion {
            get {
                return this.fecha_recepcionField;
            }
            set {
                this.fecha_recepcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pdf_justificante {
            get {
                return this.pdf_justificanteField;
            }
            set {
                this.pdf_justificanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void enviarFacturaCompletedEventHandler(object sender, enviarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPResultadoEnviarFactura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPResultadoEnviarFactura)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarFacturaCompletedEventHandler(object sender, consultarFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPResultadoConsultarFactura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPResultadoConsultarFactura)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void anularFacturaCompletedEventHandler(object sender, anularFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class anularFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal anularFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPResultadoAnularFactura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPResultadoAnularFactura)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarEstadosCompletedEventHandler(object sender, consultarEstadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEstadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEstadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPEstados Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPEstados)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarUnidadesCompletedEventHandler(object sender, consultarUnidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUnidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUnidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPResultadoConsultarUnidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPResultadoConsultarUnidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarAdministracionesCompletedEventHandler(object sender, consultarAdministracionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarAdministracionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarAdministracionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfSSPPUnidadDir Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfSSPPUnidadDir)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarUnidadesPorAdministracionCompletedEventHandler(object sender, consultarUnidadesPorAdministracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUnidadesPorAdministracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUnidadesPorAdministracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SSPPResultadoConsultarUnidades Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SSPPResultadoConsultarUnidades)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void consultarListadoFacturasCompletedEventHandler(object sender, consultarListadoFacturasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarListadoFacturasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarListadoFacturasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfSSPPResultadoConsultarFactura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfSSPPResultadoConsultarFactura)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591